apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devops-dashboard
data:
  NODE_ENV: "production"
  API_PORT: "3000"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "devops_dashboard"
